name: HealAndFeedPlugin
main: me.ncwd.healandfeedplugin.HealAndFeedPlugin
version: 1.0
api-version: 1.16
commands:
  heal:
    description: Heals Player to full
    usage: /<command>
    aliases: [healme, healmax, healing]
  feed:
    description: Feeds Player to full
    usage: /<command>
    aliases: [feedme, feedmax, feeding]